Quilt 支持
Meloong-Git/PCL pull request #4214
Opened 2024-07-09 15:35 UTC by Pigeon0v0

~先前的 PR 操作不当关了（）~

与 NeoForge 类似，本 PR 将基于先前的 Fabric 安装流程，加入针对 Quilt 的支持。
Close #48 

To-Do List: 

- [x] 在自动安装界面加入 Quilt 选项，并支持显示版本列表
- [x] Quilt 相关信息获取
- [x] 版本列表相关处理（版本排序，Quilt 相关信息显示，附加安装选项之间冲突等）
- [x] Quilt 自动安装
- [x] Quilt 手动安装界面
- [x] 相关资源文件（图标等）补充
- [x] Quilt 整合包安装
- [x] 其他界面选项和文本补充

Known Issues: 
- 手动安装包图标需要补充

**Note:** 由于 Quilt 同步 API 的问题，BMCLAPI 暂时无法用于下载 Quilt。

2024-07-09 15:36 UTC, Pigeon0v0 commented
@3gf8jv4dv 

Please have a test on features related, such as modpack installing, auto installing, etc. Appreciate!

2024-07-10 01:19 UTC, 3gf8jv4dv requested changes
1. From the API results, the lowest version supported by Quilt is only 1.14.4, but 1.14~1.14.3 can still choose Quilt. Of course, the installation is definitely unsuccessful. It is recommended that the Quilt option not be displayed for versions prior to 1.14.4.

2. In *Select Instance (版本选择)*, Quilt instances are categorized as *Fabric Instances (Fabric 版本)*

   <details>
   <summary>Preview</summary>

   ![](https://github.com/Hex-Dragon/PCL2/assets/158490944/89672b21-450f-4ddf-84da-e22daf13c0e4)

   </details>

3. Some QFAPI / QSL that are marked as supporting multiple versions (only on one platform) may not match. For example, when installing Quilt with 1.20, after selecting Quilt Loader, there are only two results in the QFAPI / QSL list. However, after filtering the corresponding projects of CurseForge / Modrinth with the *1.20* version condition, there are more results (most of which are marked as supporting 1.20~1.20.1). About `QFAPI 2.0.0-beta.1 and QSL 2.0.0-beta.8` and `QFAPI 2.0.0-beta.3 and QSL 2.0.0-beta.9`, Modrinth is marked as supporting multiple versions, but CurseForge only shows one of them, and the other shows only supporting 1.19. QFAPI / QSL are shown as empty in these game versions.

   <details>
   <summary>Preview</summary>

   ![](https://github.com/Hex-Dragon/PCL2/assets/158490944/0a15e391-9d20-4104-8397-042ca4e0bd2a)

   </details>

4. For QFAPI / QSL, the current behavior is to only display *QSL*. Strictly speaking QFAPI and QSL are different things (there is a reason why the Quilt team specifically writes this). My opinion is that you can just write *qsl* for the relevant markup within the code (like in the links on the [CurseForge](https://www.curseforge.com/minecraft/mc-mods/qsl) / [Modrinth](https://modrinth.com/mod/qsl) platform), but write *QFAPI / QSL* for the text displayed to the user.

5. Some Quilt Loader versions with `-pre` are marked as *stable (稳定版)*.

*Tried some Quilt modpacks on Modrinth and seems to be OK.*

2024-07-10 01:36 UTC, SALTWOOD commented
![image](https://github.com/Hex-Dragon/PCL2/assets/105980161/c0fece29-8dbc-4c78-8edb-0ce946d634ec)
无法选中Quilt的选项……也许是个bug？

2024-07-10 01:37 UTC, SALTWOOD commented
![image](https://github.com/Hex-Dragon/PCL2/assets/105980161/4595e479-874a-4ee9-a3df-6e8741e8dc6d)
手动安装出现错误

2024-07-10 01:47 UTC, SALTWOOD commented
> @SALTWOOD
> 
> > 无法选中Quilt的选项……也许是个bug？
> 
> I am curious about how you got triggered (I've only encountered it once, and it was inexplicable at the time, I do not know how it was triggered).
> 
> > 手动安装出现错误
> 
> > * [x]  Quilt 手动安装界面
> 
> From the author’s description, it seems to be in line with expectations, but problems do exist.
> 
> @Pigeon0v0
> 
> After writing four opinions, I suddenly found a bug, so I added it to the previous review.

I don't know. Every time I run it, the bug appears.

2024-07-10 01:49 UTC, SALTWOOD commented
也许是因为 Pages\PageDownload\PageDownloadInstall.xaml.vb Line 347-560没加？

2024-07-10 01:58 UTC, SALTWOOD commented
I turned on the catch for the `InvalidCastException` and found that this exception was thrown here:
![image](https://github.com/Hex-Dragon/PCL2/assets/105980161/9024aaad-64eb-472a-92a6-d5785d8d3b1f)
System.InvalidCastException
  HResult=0x80004002
  Message=无法将类型为“Newtonsoft.Json.Linq.JArray”的对象强制转换为类型“Newtonsoft.Json.Linq.JObject”。
  Source=Plain Craft Launcher 2
  StackTrace:
   在 PCL.ModDownload.DlQuiltListOfficialMain(LoaderTask`2 Loader) 在 C:\Users\SALTWOOD\Desktop\p\Plain Craft Launcher 2\Modules\Minecraft\ModDownload.vb 中: 第 1132 行

2024-07-10 02:00 UTC, SALTWOOD commented
both 两个bug在我这边都能稳定地复现

2024-07-10 02:05 UTC, SALTWOOD commented
@3gf8jv4dv Can you tell me what the return value of this API is like on your side?
`https://[meta.quiltmc.org/v3/versions/game](https://meta.quiltmc.org/v3/versions/game)`

2024-07-10 02:10 UTC, Pigeon0v0 commented
> ![image](https://github.com/Hex-Dragon/PCL2/assets/105980161/4595e479-874a-4ee9-a3df-6e8741e8dc6d)
> 
> 手动安装出现错误

这个 BUG 我记得我修了的...

2024-07-10 02:12 UTC, SALTWOOD commented
草，没切分支（

2024-07-10 02:17 UTC, SALTWOOD commented
我在想一个东西……就是说一部分模组在使用QFAPI加QSL的搭配的时候会无法使用，于是就会在QUILT下使用FABRIC API
而理论上quilt作为fabric的一个分支，当然是可以使用fabric API的
所以有没有必要也把fabric API的安装选项显示出来呢

2024-07-10 02:19 UTC, SALTWOOD commented
并且在同时选择了quilt和optifine之后……

2024-07-10 02:22 UTC, Pigeon0v0 commented
需要确认一下 OptiFabric 和 Quilt 的兼容情况

2024-07-10 02:27 UTC, SALTWOOD commented
那么就只能是先暂时禁用

2024-07-10 02:29 UTC, SALTWOOD commented
并且在版本选择里头安装了quilt的版本还是被识别为fabric

2024-07-10 02:29 UTC, SALTWOOD commented
> > 并且在版本选择里头安装了quilt的版本还是被识别为fabric
> 
> I mentioned this before.

all right

2024-07-10 03:33 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Resources/Custom.xaml
> +      <Image Width="30" Margin="5,0,0,0" Source="pack://application:,,,/images/Blocks/Quilt.png"/>
This should have no problem.

2024-07-10 05:26 UTC, Pigeon0v0 commented
d02adaf should solve issues mentioned above. Have a try and leave any comments! :D

@3gf8jv4dv @SALTWOOD

2024-07-10 05:46 UTC, Pigeon0v0 commented
3a1920c 顺手改了一些大小写，至少现在显示的都是 Json 和 Jar 了...

关于其他大小写和中英文空格之类的修改，日后还会再开一个 PR 之类的讨论一下...

2024-07-10 09:52 UTC, 3gf8jv4dv reviewed
No other issues encountered so far. Waiting for other people’s opinions.

2024-07-10 17:58 UTC, LTCatt requested changes
对注释、Log 和大小写的修改都没啥必要，这些都是内部写法……
因为现在的 PR 其实都是我一边手动复制到代码里一边重新整理的，所以这些注释修改最后应该也不会合进去 Orz

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb
> +        Dim InstallerResult As JArray = NetGetCodeByRequestRetry("https://meta.quiltmc.org/v3/versions/installer", IsJson:=True)
建议使用 `https://meta.quiltmc.org/v3/versions`，只需要一次请求

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
> +                        End If
原本的正则已经可以匹配了，那把 TODO 的注释删了就 OK

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +            'BMCLAPI 不支持 Quilt Installer 下载
前面加个 `'TODO: `

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                LabQSL.Text = SelectedQSL.DisplayName.Split("]")(1).Replace("Quilt API ", "").Replace(" build ", ".").Split("+").First.Trim
`.Split("+").First` 可以使用 `.Before("+")` 代替

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +                LabQSL.Text = SelectedQSL.DisplayName.Split("]")(1).Replace("Quilt API ", "").Replace(" build ", ".").Split("+").First.Trim
类似地，`.Split("]").Last` 可以使用 `.After("]")` 代替

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +        If (SelectedLoaderName = "Forge") AndAlso
不需要括号，不是 C#……

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +            If SelectedLoaderName IsNot Nothing AndAlso SelectedLoaderName IsNot "Forge" Then Return $"与 {SelectedLoaderName} 不兼容"
`If SelectedLoaderName <> "Forge" Then`
如果是 null 会返回 false 的，后面的也一样

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +        'Next
这段可以删了……？

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadLeft.xaml.vb
> +            If MyMsgBox("手动安装包功能提供了 OptiFine、Forge 等组件的 Jar 安装文件下载，但无法自动安装。" & vbCrLf &
就写 .jar 就行

2024-07-10 17:58 UTC, LTCatt commented on Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
> +                                        ToolTip="警告：强烈推荐在版本设置中关闭特定版本的校验，而不是在这里关闭所有版本的校验！&#xa;完全不更改 Assets；不校验 Libraries、第三方登录库与版本主 Jar 文件是否被修改。&#xa;如果你没有修改相关文件，请勿勾选此项。" />
这里是刻意使用小写以与文件夹名一致的

2024-07-11 04:31 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +            If SelectedLoaderName IsNot Nothing AndAlso SelectedLoaderName IsNot "Forge" Then Return $"与 {SelectedLoaderName} 不兼容"
不知道为什么改了就炸...

2024-07-11 09:46 UTC, LTCatt commented
现在堆着的有点多，我看多久动态发个投票来决定先整哪个吧……

2024-07-11 09:48 UTC, allMagicNB commented
我堆了个 Pre-Release Branch（

2024-07-11 18:57 UTC, 3gf8jv4dv requested changes

2024-07-11 23:44 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +        If SelectedMinecraftId.Contains("1.") AndAlso Val(SelectedMinecraftId.Split(".")(1)) <= 14 AndAlso Val(SelectedMinecraftId.Split(".")(2)) < 4 Then
Fixed in b9831cf.

2024-07-12 01:47 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
> +        If SelectedMinecraftId.Contains("1.") AndAlso Val(SelectedMinecraftId.Split(".")(1)) <= 14 AndAlso Val(SelectedMinecraftId.Split(".")(2)) < 4 Then
Fixed in 7a2478b.

2024-07-14 13:59 UTC, 3gf8jv4dv reviewed
Now selecting `1.14` no longer crashes. 👍 

No other issues have been found so far. Waiting for others’ opinions.

2024-07-14 14:07 UTC, 3gf8jv4dv requested changes
It seems that if you select `1.14.4` for the first time after opening the launcher, a strange scene will appear in the UI. Or select a version before 1.14.4 and then select `1.14.4` and it will also appear. It will be normal if you select a higher version and then select `1.14.4`.

<details>
<summary>Preview</summary>

![](https://github.com/user-attachments/assets/dd16017e-b24c-4de5-a387-77b7b08a59ad)

</details>

2024-07-14 14:10 UTC, Pigeon0v0 commented
I don't know why it happens... 

Wait for LTCatt. I have no computer at my hands right now.

2024-07-15 11:18 UTC, Pigeon0v0 commented
In my opinion, QSL / QFAPI is designed specially for Quilt, and it can replace Fabric API, so I didn't let Fabric API appear after you have selected Quilt.

2024-07-15 11:49 UTC, hejiehao commented
> In my opinion, QSL / QFAPI is designed specially for Quilt, and it can replace Fabric API, so I didn't let Fabric API appear after you have selected Quilt.

有一些 Minecraft 版本 QFAPI 不支持或者更新速度较慢，这个时候可以用 Fabric API 来替代

2024-07-15 11:52 UTC, Pigeon0v0 commented
> 有一些 Minecraft 版本 QFAPI 不支持或者更新速度较慢，这个时候可以用 Fabric API 来替代

好的，有空了改（

2024-07-19 08:11 UTC, Pigeon0v0 commented
Done in 6d88559. 

Now Fabric API is able to be selected with Quilt selected. I've also added a hint when you select both Quilt and Fabric API, but QSL is actually available. If QSL is not available, Fabric API will be selected automatically. 

@3gf8jv4dv @hejiehao Have a test and leave comments. :)

<details>
<summary>Preview</summary>

![image](https://github.com/user-attachments/assets/261686f9-301c-47fa-8c42-be24742ccecf)

![image](https://github.com/user-attachments/assets/437c38ed-fec7-48ff-8436-3bb6843c8069)

![image](https://github.com/user-attachments/assets/19355aec-2892-4b5f-abf4-c8d75c64d4d8)

![image](https://github.com/user-attachments/assets/1a11a1ec-dcca-4f29-871f-08f57580ea43)
</details>

2024-07-19 14:44 UTC, Deep-Dark-Forest requested changes

2024-07-19 14:44 UTC, Deep-Dark-Forest commented on Plain Craft Launcher 2/Modules/Base/ModBase.vb
> +                        Throw New Exception("不是有效的 Json 文件", ex)
为什么不是 JSON？

2024-07-19 15:20 UTC, Pigeon0v0 commented on Plain Craft Launcher 2/Modules/Base/ModBase.vb
> +                        Throw New Exception("不是有效的 Json 文件", ex)
这没必要...

2024-07-19 16:13 UTC, 3gf8jv4dv reviewed
Has a UI issue, otherwise looks good. (Not sure if it can be fixed)

**EDIT:** *This also happens with Fabric Loader.*

<details>
<summary>Preview</summary>

![](https://github.com/user-attachments/assets/043f0625-e8c4-4fe6-9295-a8aed477698c)

</details>

2024-07-20 01:05 UTC, Pigeon0v0 commented
I don't know how it happens...

2024-07-20 06:47 UTC, JingHai-Lingyun commented
button event binding issue?

2024-08-09 00:44 UTC, JingHai-Lingyun commented
I this #1784 need another pr. 
Because if it can detector mods in folder, ui may has changes.

2024-09-22 01:33 UTC, allMagicNB requested changes

2024-09-22 01:33 UTC, allMagicNB commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +
？

2026-07-17 09:37 UTC, LTCatt commented
经过调查，目前 Quilt 的全球使用率仅为 ~2%，且近年的使用率还在持续下滑，半身入土，已经没有兼容的必要了

2026-07-17 09:37 UTC, closed without merging

2026-07-17 09:59 UTC, 3gf8jv4dv commented
> 经过调查，目前 Quilt 的全球使用率仅为 ~2%，且近年的使用率还在持续下滑，半身入土，已经没有兼容的必要了

有点好奇数据怎么来的。

不过不统计也能感受到 QuiltMC 的没落了。