新功能：加入一系列简单的管理版本资源界面
Meloong-Git/PCL pull request #4770
Opened 2024-09-21 08:05 UTC by tangge233

## 前言
PCL2 竟然这么久还没有简单的版本资源管理界面

## 进度
- [ ] 存档管理
- [x] 截图管理
- [ ] 资源包管理
- [ ] 光影管理

## 其它一些话

很显然这打扰到了 PCL2 的一些功能开发进度，所以这可能长期不能被合并
~~毕竟功能还没写好~~

2024-09-21 08:14 UTC, tangge233 commented
不会加入非常复杂的内容，只有简单的查看（不会有非常详细的信息）、删除、另存为什么的……

2024-09-21 08:35 UTC, LTCatt commented
我自己应该不会考虑添加这些功能……不过可以加进 PR Collection 啥的（

2024-09-21 09:54 UTC, allMagicNB commented
刚发现 [7965ca8](https://github.com/Hex-Dragon/PCL2/pull/4555/commits/7965ca818d1d5bc0ec182df211c1824f45ee8c7e) 干爆了我 PR Collection
![image](https://github.com/user-attachments/assets/b119a7a2-b6c0-4e2f-b6be-a6e4a4dd4a0a)

2024-09-21 13:46 UTC, Chiloven945 commented
![49968108b860962881a25b0028d16305](https://github.com/user-attachments/assets/56115978-cfee-4b85-b522-0dd4e954ae2f)
目前的图标对个人来说比较丑，因为 PCL 总体图标风格不存在面的元素
所以说建议：
资源包
![resource-two资源2](https://github.com/user-attachments/assets/2fb979da-5543-4082-bd58-b30fbe06f4d8)
光影
![lightbulb-alt](https://github.com/user-attachments/assets/0a2bfb2b-623c-45dd-982f-e4b7ab5ef096)
![lightbulb--lighting-light-incandescent-bulb-lights](https://github.com/user-attachments/assets/c79e85bb-b750-4c28-a9de-60fa9af21421)
![paint](https://github.com/user-attachments/assets/0e6b3ddb-7a9d-458c-95d4-31a16e52c905)
![light-bulb](https://github.com/user-attachments/assets/2032a34d-8c11-4302-9359-1e956b347d4b)

2024-09-21 14:10 UTC, 3gf8jv4dv requested changes
When I click on the resource pack
```
程序出现未知错误：Could not find a part of the path '*:\PCL\.minecraft\versions\*\PCL\Resourcepacks\'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at PCL.PageVersionResourcePack.LoadFileList()
   at PCL.PageVersionResourcePack.Reload()
   at PCL.PageVersionResourcePack.PageSetupLaunch_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.IO.DirectoryNotFoundException
```

2024-09-21 14:17 UTC, 3gf8jv4dv reviewed
Some opinions.

After copying the screenshot, no screenshot is seen in the `Win`+`V` clipboard interface. However, the screenshot function of some software can be used to view the corresponding screenshot on the above interface after taking the screenshot. Is it possible to implement it here?

For each screenshot in the screenshot interface, can you add rounded corners around the preview? The current effect looks a bit abrupt compared to the UI elements.

2024-09-21 14:43 UTC, tangge233 commented
@3gf8jv4dv 

When I try to add rounded corners around the picture, the UI becomes strange.

![image](https://github.com/user-attachments/assets/a608a7fe-d863-4668-980b-89bb1ab7fa56)

---

And there seems some issues with windows clipboard, it does not work very well sometimes.

2024-09-21 15:48 UTC, tangge233 commented on Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb
> +                    Clipboard.Clear()
https://github.com/tangge233/PCL2/blob/1aaf37f81528e98bb9c8ba6cfe3e8e67af00cb60/Plain%20Craft%20Launcher%202/Modules/Base/ModBase.vb#L2227

I found the code in `ModBase.vb` do like this.

2024-09-21 19:17 UTC, allMagicNB commented
换下 Page ID 吧，与导出整合包页面冲突了（

2024-09-21 23:19 UTC, tangge233 commented
> 换下 Page ID 吧，与导出整合包页面冲突了（

你改下呀…

2024-09-22 01:03 UTC, allMagicNB commented
> > 换下 Page ID 吧，与导出整合包页面冲突了（
> 
> 你改下呀…

你不换到时候也要解决冲突（

2024-09-22 05:07 UTC, 3gf8jv4dv requested changes
剪切板 → 剪贴板

Follow the practices in Microsoft Windows zh-CN language.

2024-09-22 05:16 UTC, 3gf8jv4dv requested changes

2024-09-22 13:23 UTC, tangge233 commented
现在应该没什么问题了。
很轻量级的功能，龙猫考虑下？

2024-09-23 06:51 UTC, LTCatt commented
优先度会非常非常低 =。=

2024-09-23 09:24 UTC, 3gf8jv4dv requested changes

2025-01-25 14:52 UTC, tangge233 commented
经过多轮开发，此 PR 已较完善实现相关功能

2025-01-27 03:50 UTC, Txt-Text commented
几个月了，所以这个功能最终会合并到正式版吗🤔

2025-01-27 03:58 UTC, tangge233 commented
> 几个月了，所以这个功能最终会合并到正式版吗🤔

会的。

最近社区版测试出了这个功能一些小问题，近期还会同步一次修复代码到这里（

2025-02-17 07:21 UTC, LTCatt commented
资源包和光影包其实可以完全按照 Mod 页面的方式来，它们也可以获取到 CF/Modrinth 上的工程，所以也可以跳转到详情页面以及更新啥的。
截图和存档管理我觉得确实没啥必要，加个打开文件夹入口感觉就够了，可能之后也不会合……

2025-02-19 11:24 UTC, LTCatt commented
Mod/资源包/光影包 的代码确实建议合并到一个 Page，不然会重复三次……

2025-02-20 12:02 UTC, tangge233 commented
目前效果 ~~还不错，除了 Curseforge 不听话以外……~~

![image](https://github.com/user-attachments/assets/b63b59f1-7059-47ab-ae9c-c19c558140d8)

2025-03-15 06:26 UTC, tangge233 commented
此功能在 CE 测试时发现了 CurrentLoader 不更新问题，比较棘手，正在寻找更好实现方法……

2025-04-29 10:33 UTC, LTCatt commented
可以参考 2.10.0 中的 PageComp 的形式统一 Mod/资源包/光影包 的代码……（

2025-04-30 12:07 UTC, tangge233 commented
目前有个问题。光影包和材质包可以以文件夹的形式存在，但是目前只有基于文件的资源逻辑。是否需要考虑兼容文件夹形式存在的资源？🤔

2025-05-04 21:00 UTC, LTCatt commented
> 目前有个问题。光影包和材质包可以以文件夹的形式存在，但是目前只有基于文件的资源逻辑。是否需要考虑兼容文件夹形式存在的资源？🤔

这种感觉可以不管……

2026-07-18 16:34 UTC, closed without merging